table Orders
	lineageTag: b8fbdb2a-caa3-4b0a-bd5e-a3490849f0da

	measure 'Total Profit' = sum(Orders[Profit])
		lineageTag: 0df7e4a7-9409-46be-9428-4801b191adb1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales' = sum(Orders[Sales])
		lineageTag: 91505828-6cdd-4e52-9cec-075b108c30f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 3a8892dc-398a-4574-8eb1-d3e6a2fcf471
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: a75803ad-c36e-4fb7-b893-c79f3fae38ce
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: da45bdf4-b939-4ba0-bb03-6cadf77b97d0
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 2a1c1bd5-0455-4eac-86d9-0dbc84eb9973
			defaultHierarchy: LocalDateTable_f1e44750-a379-48a2-bc62-9427211221b5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4fc5d43-9ac9-4798-b7ea-4928c44bc585
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 498a940f-5dee-4d8a-8719-e16348e666a8
			defaultHierarchy: LocalDateTable_4e390a20-6fa6-425b-b3b5-d859a5a1bbe0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: f7941918-2bb0-41c1-bb64-49bae53e2d9d
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: b3344f7c-b665-44be-8941-df310f9fd0a4
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 024c8ccc-6395-4864-87c8-4c24e536271b
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 269b16bf-ca99-458b-b7bc-b0656db8733e
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: e50a726a-4e24-4e78-bb1f-f92ebc4b8e85
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 61d8d112-bef2-49c2-870a-712459c26573
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: cebc3d2e-bdbf-45a0-8825-0b0d4843143c
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: ec2924b9-4cbb-478a-9e84-284e00ec625e
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 468a6188-002b-43e5-abfa-d25881bacf9c
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 84f95815-6f70-4671-bd5f-7b40567527a4
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9b8f3905-bf64-430c-95da-da6d023aea33
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 92b167d9-6d40-43d2-9c1c-c7d2141d32c4
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 308091f3-aa6d-42dd-a5df-5ed038cd9fea
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 5be76748-866e-45fb-94dc-4314132a8b7e
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: e0d8c4c5-fefd-49ff-89d8-bf9094c4146e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: d56434c2-6203-45a6-a7d0-95d5dddf5af5
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 3ffc7762-16f1-4efb-92cd-0f7e598f0b0b
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Sample Superstore\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

